# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-30 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a name for the event.', max_length=50)),
                ('description', models.CharField(help_text='Enter a brief description of the event.', max_length=500)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('local_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.UUIDField(default=uuid.uuid4, help_text='unique way to identify each project.', primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a unique skill (e.g. programming, dancing, etc.)', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(help_text='Enter a unique tag/keyword (e.g. programming, dancing, etc.)', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('id', models.UUIDField(default=uuid.uuid4, help_text='unique way to identify each user.', primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50)),
                ('projects_owned', models.ManyToManyField(help_text='Select a project that this user owns.', to='rendezvous.Project')),
                ('relevant_skills', models.ManyToManyField(help_text='Select one of your relevant skills.', to='rendezvous.Skill')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='contributors',
            field=models.ManyToManyField(help_text='User that is contributing to this project.', to='rendezvous.User'),
        ),
        migrations.AddField(
            model_name='project',
            name='events',
            field=models.ManyToManyField(to='rendezvous.Event'),
        ),
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rendezvous.Location'),
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to='rendezvous.User'),
        ),
        migrations.AddField(
            model_name='project',
            name='skills_desired',
            field=models.ManyToManyField(help_text='Select one of the relevant skills that you are looking for.', to='rendezvous.Skill'),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(help_text='Select relevant tags so users can find your project.', to='rendezvous.Tag'),
        ),
    ]
