# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-31 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendezvous', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date_completed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='date_created',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='contributors',
            field=models.ManyToManyField(blank=True, help_text='User that is contributing to this project.', to='rendezvous.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='projects_owned',
            field=models.ManyToManyField(blank=True, help_text='Select a project that this user owns.', to='rendezvous.Project'),
        ),
    ]
