# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 01:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rendezvous', '0004_user_account'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Profile',
        ),
    ]
